#ifndef __ITENSOR_CONFIG_H
#define __ITENSOR_CONFIG_H

#ifndef PLATFORM_lapack
#define PLATFORM_lapack
#endif

#ifndef __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES
#define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

#endif 